### ISSUE TITLE
igx-grid binding to remote service

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/ignite-ui-docfx#20]
Create an example on how to bind the `igx-grid` to a remote service, and how to perform filtering, sorting and paging operations on the back-end.

**Comment by rkaraivanov** [comment]
Performing data operations on the back-end is well for the back-end 😉

**Comment by kdinev** [comment]
What I meant is ti display how to organize the requests through the http module of angular. Not so much how to organize the back-end to return the data.
